sudo: required

language: java

services:
  - docker

branches:
  only:
    - travis

notifications:
  email: false
  slack:
    secure: ZmZzTUatbc//9bkZCpxvPkqae+OedCLxtBKsqjoj8bZJz3Ciw/ieHByXXbYCiKxcFjf1lSmc2yFWNSOkjBU3elHYy7F+CD7kUJjZhlCZIW592rOd7/n2Bs3bUSZXbTV0dDB9EeQRLeG7rXZuFaa2k9GHLu2GRrG21nL695QCk7xTsbp8vADr+JBCurmROUHznbp0HUQwm06PnflRRq749hDN9tyXWaDxZg7pwDMrhtodkox9KgSKtm0acZy3fPUk4Prf1kZastKXewo2/dweoiihwAe+fXXsMA+zdMSA5dWxoE5CQGvrRVGvXmSr0oZyHC9Fhftkt/emetmO1VC+ERaBT3UwcY1yRyOtigC4hzgUghmwfiEHAFiUbekcDnxcACsBiv3WJ+IEVpsvYNVbwxdlKBpJ/H/3tuDklZTPUe8BHqTKQg40S3kvVAYKuawRF4kaYvaCKK0DH9BtFL79h/juVT0aGzRyIV1GWBxeyKf6yhoGjvkRY7otkdKWyiMrIXvorADs5JKcqI4itxwtbBq7T9craSRnQnAlFs/8TBe15z9yDuyHN6tMwnXidT/uy+R/vBEIodT4BxB52/u9EbkXWszdJTZcrWnz6Csop9pia7ja+OCcH67VJ/ZDiVORCw5BVB19FGUYpd5oAmEe2/ZAbqRa0eMZp+LXzwTppr0=

before_install:
  - mvn clean package
  - docker build -t patrykks/iosr-excel-export-service .
  - docker run --name excelexportservice -d patrykks/iosr-excel-export-service

script:
  - docker ps | grep -q excelexportservice
  - docker exec excelexportservice mvn -f /webapp/excel-export-service/pom.xml test

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push patrykks/iosr-excel-export-service;
    fi