FROM maven:3-jdk-8-slim
COPY "target/excel-export-service-1.0-SNAPSHOT.jar" "/webapp/"
EXPOSE 4444
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /webapp/excel-export-service-1.0-SNAPSHOT.jar $APP_OPTS" ]

